version: '3'

services:
  backend:
    image: 090664031164.dkr.ecr.eu-north-1.amazonaws.com/converter-backend:latest
    environment:
      - CONVERTER_SERVICE=http://conversion-service:5353
    ports:
      - "8080:8080"

  conversion-service:
    image: 090664031164.dkr.ecr.eu-north-1.amazonaws.com/convertor-file-conversion:latest
    ports:
      - "5353:5353"

  web:
    image: 090664031164.dkr.ecr.eu-north-1.amazonaws.com/converter-frontend:latest
    ports:
      - "5001:5001"



